apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  namespace: evaluation-system
spec:
  # LoadBalancer : Grafana doit être accessible depuis le navigateur
  type: LoadBalancer
  selector:
    app: grafana
  ports:
    - port: 3000
      targetPort: 3000
