apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: evaluation-system
spec:
  # ClusterIP : Prometheus n'a pas besoin d'être accessible depuis internet
  # Grafana y accède via le réseau interne du cluster
  type: ClusterIP
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
